return {}
-- tailwind-autosort.lua
-- return {
--   "y3owk1n/tailwind-autosort.nvim",
--   version = "*", -- remove this if you want to follow `main` branch
--   event = "VeryLazy",
--   dependencies = { "nvim-treesitter/nvim-treesitter" },
--   ---@type TailwindAutoSort.Config
--   opts = {
--
--     -- enabling autocommand will let tailwind-autosort to update the text at 'BufWritePre'
--     -- If your editor does format on save after write, it should work together
--     enable_autocmd = false,
--     -- This option will notify you number of lines that is affected via vim.notify
--     notify_line_changed = true,
--   }, -- your configuration
-- }
